version: '3'

services:
  nginx-laravel:
    container_name: nginx-laravel
    image: nginx:latest
    ports:
      - "8005:80"
    volumes:
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./case/laravel:/var/www/html
    depends_on:
      - php-laravel

  nginx-symfony:
    container_name: nginx-symfony
    image: nginx:latest
    ports:
      - "8006:80"
    volumes:
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./case/symfony:/var/www/html
    depends_on:
      - php-symfony

  php-laravel:
    container_name: php-laravel
    build:
      context: ./docker/php
    volumes:
      - ./case/laravel:/var/www/html
    entrypoint: ["sh", "/var/www/html/entrypoint.sh"]
    depends_on:
      - mysql-laravel

  php-symfony:
    container_name: php-symfony
    build:
      context: ./docker/php
    volumes:
      - ./case/symfony:/var/www/html
    entrypoint: ["sh", "/var/www/html/entrypoint.sh"]
    depends_on:
      - mysql-symfony

  mysql-laravel:
    container_name: mysql-laravel
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: is_case_laravel
      MYSQL_DATABASE: is_case_laravel
      MYSQL_USER: is_case_laravel
      MYSQL_PASSWORD: is_case_laravel
    volumes:
      - ./docker/mysql/laravel_example.sql:/docker-entrypoint-initdb.d/example.sql
    ports:
      - "3309:3306"

  mysql-symfony:
    container_name: mysql-symfony
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: is_case_symfony
      MYSQL_DATABASE: is_case_symfony
      MYSQL_USER: is_case_symfony
      MYSQL_PASSWORD: is_case_symfony
    volumes:
      - ./docker/mysql/symfony_example.sql:/docker-entrypoint-initdb.d/example.sql
    ports:
      - "3310:3306"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"