version: '3'

services:
  nginx-laravel:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8005:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./case:/var/www/html
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./case:/var/www/html
    entrypoint: ["sh", "/var/www/html/entrypoint.sh"]
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: is_case
      MYSQL_DATABASE: is_case
      MYSQL_USER: is_case
      MYSQL_PASSWORD: is_case
    volumes:
      - ./docker/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql
    ports:
      - "3309:3306"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"